M48
; DRILL file {KiCad 9.0.2} date 2025-06-25T17:31:34+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-25T17:31:34+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.991
%
G90
G05
T1
X98.75Y-102.11
X98.75Y-107.89
T2
X116.484Y-124.81
X117.5Y-117.19
X118.516Y-124.81
M30
